# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  #build:
  tests: #Se va a incluir tests
    name: Tests #nombre tests
    runs-on: ubuntu-latest #version en la que se va a correr el tests
    #Los pasos en los que va a realizar el despliegue
    steps:
    - uses: actions/checkout@v4
    #- name: Set up JDK 17
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        #java-version: '17'
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    #Esto que sigue es el paso a paso de como va a correr todo, si queremos correr el aplicativo o tambien correr el tests
    #- name: Build with Maven
    #run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn -B test
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build app
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: target/testseleniumandcicd-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu:latest

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: artifact
     #------------------------------------------------------------
     # - name: Deploy to EBS #Debo recordar que esto es para el despliegue en aws con elastic
     #   uses: einaregilsson/beanstalk-deploy@v22 #Recordar que esta version es de aws con elastic y pueden cambiar de version
     #   with:
     #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} #Debo recordar que esta en mi aws configuraciones
     #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #Debo recordar que esta en mi aws configuraciones
     #     application_name: testseleniumandcicd #Debo recordar que este es el nombre del aplicativo o app que quedo en aws con elastic
     #     environment_name: testseleniumandcicd-env #Debo recordar que este es el env que aparece en entornos de aws con elastic
     #     version_label: ${{ github.SHA }} #Recordar que esta version la va a copiar de sha que genera github al subir el deploy
     #     region: us-east-1 #Recordar que este es el pais o ubicacion donde se desplego el app en aws con elastic
     #     deployment_package: testseleniumandcicd-0.0.1-SNAPSHOT.jar #Recordar que este ya es el archivo que se subir y ahora se descargo para poder ejecutarlo en aws con elastic
     #------------------------------------------------------------
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6